### ISSUE TITLE
Expose external port or LoadBalance in Service-deployment and Create gRPC client

### ISSUE THREAD

**Issue by politrons** [cloudstateio/cloudstate#136]
Hi

After deploy my service in cloudstate, how to make the `shopping-cart-deployment` expose an `external ip` or `LB` to connect with `grpcCurl` or `gRPC client` ?

I also implement an gRCP client to consume the Service
following the code example that you guys implement.

https://github.com/cloudstateio/cloudstate/blob/master/samples/akka-client/src/main/scala/io/cloudstate/samples/ShoppingCartClient.scala

I cannot figure how your proto file generate the `com.example.shoppingcart.shoppingcart.ShoppingCartClient(settings)`

Normally when you use google grpc it create client/service side sources to communicate each othrer.
 Here in the `shoppingCart` example with protocol and domain, only service code is generated but not client.

Any idea what to do?

**Comment by politrons** [comment]
I tried to change the Service yaml to make it works with LoadBalance but after change it and deploy it

```
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: cloudstate-shopping-cart
spec:
  type: LoadBalancer
  ports:
    - port: 1981
      targetPort: 8013
  datastore:
    name: inmemory
  containers:
    - image: politrons/shopping-cart:latest

---
```
And check the service service description  `kubectl describe service cloudstate-shopping-cart`

The service still run in ClusterIp so is unreachable

```
Name:              cloudstate-shopping-cart
Namespace:         cloudstate
Labels:            app.kubernetes.io/managed-by=cloudstate.io
Annotations:       <none>
Selector:          cloudstate.io/statefulServiceUID=f9ebc530-fab1-11e9-a48c-025000000001
Type:              ClusterIP
IP:                10.108.72.118
Port:              grpc  80/TCP
TargetPort:        8013/TCP
Endpoints:         10.1.0.197:8013
Session Affinity:  None
Events:            <none>
```

Any idea why type  type: LoadBalancer is not working here?. 

I think I'm gonna need to study pretty hard K8s before can play with cloudstate :( 

Regards

**Comment by viktorklang** [comment]
@politrons Hmmm, perhaps we should add a straightforward example of adding this. @jroper wdyt?

**Comment by politrons** [comment]
From my side I would continue studying K8s which is good, and If I manage to run the service with a LoadBalance I can provide you the example.

**Comment by jroper** [comment]
Firstly, a Cloudstate `StatefulService` and a Kubernetes `Service` are two completely different things, the former is something that gets deployed (like a Kubernetes `Deployment`), the latter is something that helps traffic routing. `type: LoadBalancer` has no place in a `StatefulService` descriptor, no do the `ports` declarations.

We do need to come up with a better story for this. Cloudstate will automatically deploy a `ClusterIP` service for you, which works when using Istio (you then deploy an Istio gateway and virtual service, and access it through your istio ingress gateway). It also will work in most circumstances when using a k8s `Ingress`, though I think on GKE for example, it's better to deploy `NodePort` so that the GCP load balancer can route traffic directly to your node.

So, we can do the following: make the type of service deployed configurable, or perhaps we shouldn't deploy a service at all and let it always be up to the user.

But, for now, simply deploy your own `Service` (with a different name of course), here I'll show both the `StatefulService` and the corresponding `Service`:

```yaml
apiVersion: cloudstate.io/v1alpha1
kind: StatefulService
metadata:
  name: cloudstate-shopping-cart
  labels:
    app: cloudstate-shopping-cart
spec:
  datastore:
    name: inmemory
  containers:
    - image: politrons/shopping-cart:latest
---
apiVersion: v1
kind: Service
metadata:
  name: cloudstate-shopping-cart-service
spec
  type: LoadBalancer
  ports:
    - port: 1981
      targetPort: 8013
  selector:
    app: cloudstate-shopping-cart
```
