### ISSUE TITLE
Cloudstate CRDs should probably use a sub-domain for API group

### ISSUE THREAD

**Issue by jsravn** [cloudstateio/cloudstate#145]
The current CRD is defined like this:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: statefulstores.cloudstate.io
spec:
  group: cloudstate.io
```

This seems to break convention of defining a CRD group as a sub-domain of the  domain. Examples are [Istio](https://github.com/istio/istio/blob/f1e6a60efc3c42b5b4fe7a15f8a66e97352314e1/install/kubernetes/helm/istio-init/files/crd-mixer.yaml#L15) which uses `config.istio.io`, [Prometheus](https://github.com/coreos/prometheus-operator/blob/f94728d25fb61a466e3736e640be6415ed0545ed/example/prometheus-operator-crd/podmonitor.crd.yaml#L8) which uses `monitoring.coreos.com`.

I ran into this because `kubebuilder` expects the domain of the CRD to be a top level domain, with the API group as a sub-domain. So it thinks this CRD's domain is `io`.

I think technically this is allowed, but as convention seems indicate using a sub-domain, we should consider changing it to prevent future incompatibilities with tools and changes to k8s itself.
